[package]
name = "swoon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
console = "0.15.0"
dialoguer = "0.9.0"
liquid = "0.23.0"
which = "4.2.2"
